/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TenantManagementImport } from './routes/tenant-management'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TenantManagementRoute = TenantManagementImport.update({
  path: '/tenant-management',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tenant-management': {
      id: '/tenant-management'
      path: '/tenant-management'
      fullPath: '/tenant-management'
      preLoaderRoute: typeof TenantManagementImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  TenantManagementRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tenant-management"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tenant-management": {
      "filePath": "tenant-management.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
