import { createRoute, redirect } from '@tanstack/react-router';

/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes
import App from './App/App';
import rootRoute from './App/routes/__root';

// Create/Update Routes

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {}
}

// Create and export the route tree

const mainRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: 'tenant-management',
  component: App,
});

const appRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  loader: () => {
    return redirect({
      to: '/tenant-management',
    });
  },
});

export const routeTree = rootRoute.addChildren({ appRoute, mainRoute });

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": []
    }
  }
}
ROUTE_MANIFEST_END */
